export function getLetterGrade(percentage: number): string {
  if (percentage >= 90) return 'A+'
  if (percentage >= 85) return 'A'
  if (percentage >= 80) return 'A-'
  if (percentage >= 77) return 'B+'
  if (percentage >= 73) return 'B'
  if (percentage >= 70) return 'B-'
  if (percentage >= 67) return 'C+'
  if (percentage >= 63) return 'C'
  if (percentage >= 60) return 'C-'
  if (percentage >= 57) return 'D+'
  if (percentage >= 53) return 'D'
  if (percentage >= 50) return 'D-'
  return 'F'
}
